package com.shangsc.platform.model;

import com.shangsc.platform.core.model.Condition;
import com.shangsc.platform.core.model.Operators;
import com.shangsc.platform.core.util.CommonUtils;
import com.shangsc.platform.core.view.InvokeResult;
import com.shangsc.platform.model.base.BaseAd;

import java.util.*;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ad extends BaseAd<Ad> {
	public static final Ad dao = new Ad();

	public InvokeResult save(Long id, String title, String content, String imgUrl, Integer status, String userName) {
		if (null != id && id > 0l) {
			Ad ad = this.findById(id);
			if (ad == null) {
				return InvokeResult.failure("更新广告失败, 该广告不存在");
			}
			ad = setProp(ad, title, content, imgUrl, status, userName);
			ad.update();
		} else {
			Ad ad = new Ad();
			ad = setProp(ad, title, content, imgUrl, status, userName);
			ad.save();
		}
		return InvokeResult.success();
	}

	private Ad setProp(Ad ad, String title, String content, String imgUrl, Integer status, String userName) {
		ad.setTitle(title);
		ad.setContent(content);
		ad.setImgUrl(imgUrl);
		ad.setStatus(status);
        ad.setCreateUser(userName);
        ad.setCreateTime(new Date());
		return ad;
	}

	public InvokeResult deleteData(String idStrs) {
		List<Long> ids = CommonUtils.getLongListByStrs(idStrs);
		for (int i = 0; i < ids.size(); i++) {
			this.deleteById(ids.get(i));
		}
		return InvokeResult.success();
	}


	public InvokeResult changePublishStatus(Integer status) {
		Set<Condition> conditions = new HashSet<Condition>();
		conditions.add(new Condition("status", Operators.EQ, 1));
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("status", status);
		this.update(conditions, map);
		return InvokeResult.success();
	}
}
