package com.shangsc.platform.model;

import com.jfinal.plugin.activerecord.Db;
import com.shangsc.platform.code.YesOrNo;
import com.shangsc.platform.core.util.CommonUtils;
import com.shangsc.platform.core.view.InvokeResult;
import com.shangsc.platform.model.base.BaseAd;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ad extends BaseAd<Ad> {
    public static final Ad dao = new Ad();

    public InvokeResult save(Long id, String title, String content, String imgUrl, Integer status, String userName) {
        if (null != id && id > 0L) {
            Ad ad = this.findById(id);
            if (ad == null) {
                return InvokeResult.failure("更新公告失败, 该公告不存在");
            }
            ad = setProp(ad, title, content, imgUrl, status, userName);
            //if (YesOrNo.isYes(String.valueOf(status))) {
            //    offPublishOther();
            //}
            ad.update();
        } else {
            Ad ad = new Ad();
            ad = setProp(ad, title, content, imgUrl, status, userName);
            //if (YesOrNo.isYes(String.valueOf(status))) {
            //    offPublishOther();
            //}
            ad.save();
        }
        return InvokeResult.success();
    }

    private void offPublishOther() {
        Db.update("update t_ad set status=0 where 1=1");
    }

    private Ad setProp(Ad ad, String title, String content, String imgUrl, Integer status, String userName) {
        ad.setTitle(title);
        ad.setContent(content);
        ad.setImgUrl(imgUrl);
        ad.setStatus(status);
        ad.setCreateUser(userName);
        ad.setCreateTime(new Date());
        return ad;
    }

    public InvokeResult deleteData(String idStrs) {
        List<Long> ids = CommonUtils.getLongListByStrs(idStrs);
        for (int i = 0; i < ids.size(); i++) {
            this.deleteById(ids.get(i));
        }
        return InvokeResult.success();
    }

    public InvokeResult publish(Long id, Integer isCancel) {
        if (isCancel == 0) {
            Ad first = this.findFirst("select count(1) as TotalCount from t_ad where status=1");
            if (first != null) {
                Long totalCount = first.get("TotalCount");
                if (totalCount == 1) {
                    return InvokeResult.failure("发布公告失败, 发布公告数已达上限1个！");
                }
            }
        }
        Ad ad = this.findById(id);
        if (ad == null) {
            return InvokeResult.failure("更新公告失败, 该公告不存在");
        }

        if (isCancel == 1) {
            ad.setStatus(0);
            ad.setMemo("取消发布");
        }
        if (isCancel == 0) {
            ad.setStatus(1);
            ad.setMemo("已发布");
        }
        //offPublishOther();
        ad.update();
        return InvokeResult.success();
    }
}
