package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Image extends BaseImage<Image> {
	public static final Image dao = new Image();
}
