package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseLawRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LawRecord extends BaseLawRecord<LawRecord> {
	public static final LawRecord dao = new LawRecord();
}
