package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseMsgReceiver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgReceiver extends BaseMsgReceiver<MsgReceiver> {
	public static final MsgReceiver dao = new MsgReceiver();
}
