package com.shangsc.platform.model;

import com.shangsc.platform.model.base.BaseSupplyUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplyUnit extends BaseSupplyUnit<SupplyUnit> {
	public static final SupplyUnit dao = new SupplyUnit();
}
