package com.shangsc.platform.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.shangsc.platform.core.model.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgReceiver<M extends BaseMsgReceiver<M>> extends BaseModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setMsgId(Long msgId) {
		set("msg_id", msgId);
	}

	public Long getMsgId() {
		return get("msg_id");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setReceiverId(Long receiverId) {
		set("receiver_id", receiverId);
	}

	public Long getReceiverId() {
		return get("receiver_id");
	}

	public void setReceiverName(String receiverName) {
		set("receiver_Name", receiverName);
	}

	public String getReceiverName() {
		return get("receiver_Name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
