package com.shangsc.platform.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.shangsc.platform.core.model.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLawRecord<M extends BaseLawRecord<M>> extends BaseModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setLongitude(java.math.BigDecimal longitude) {
		set("longitude", longitude);
	}

	public java.math.BigDecimal getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.math.BigDecimal latitude) {
		set("latitude", latitude);
	}

	public java.math.BigDecimal getLatitude() {
		return get("latitude");
	}

	public void setInnerCode(String innerCode) {
		set("inner_code", innerCode);
	}

	public String getInnerCode() {
		return get("inner_code");
	}

	public void setUserId(Integer userId) {
		set("user_id", userId);
	}

	public Integer getUserId() {
		return get("user_id");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}

	public String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
