package com.shangsc.platform.model.base;

import com.shangsc.platform.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompany<M extends BaseCompany<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setInnerCode(java.lang.String innerCode) {
		set("inner_code", innerCode);
	}

	public java.lang.String getInnerCode() {
		return get("inner_code");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setStreet(java.lang.Integer street) {
		set("street", street);
	}

	public java.lang.Integer getStreet() {
		return get("street");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setCustomerType(java.lang.Integer customerType) {
		set("customer_type", customerType);
	}

	public java.lang.Integer getCustomerType() {
		return get("customer_type");
	}

	public void setWaterUseType(java.lang.Integer waterUseType) {
		set("water_use_type", waterUseType);
	}

	public java.lang.Integer getWaterUseType() {
		return get("water_use_type");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return get("contact");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setPostalCode(java.lang.String postalCode) {
		set("postal_code", postalCode);
	}

	public java.lang.String getPostalCode() {
		return get("postal_code");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setWellCount(java.lang.Integer wellCount) {
		set("well_count", wellCount);
	}

	public java.lang.Integer getWellCount() {
		return get("well_count");
	}

	public void setFirstWatermeterCount(java.lang.Integer firstWatermeterCount) {
		set("first_watermeter_count", firstWatermeterCount);
	}

	public java.lang.Integer getFirstWatermeterCount() {
		return get("first_watermeter_count");
	}

	public void setRemotemeterCount(java.lang.Integer remotemeterCount) {
		set("remotemeter_count", remotemeterCount);
	}

	public java.lang.Integer getRemotemeterCount() {
		return get("remotemeter_count");
	}

	public void setUnitType(java.lang.Integer unitType) {
		set("unit_type", unitType);
	}

	public java.lang.Integer getUnitType() {
		return get("unit_type");
	}

	public void setLongitude(java.math.BigDecimal longitude) {
		set("longitude", longitude);
	}

	public java.math.BigDecimal getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.math.BigDecimal latitude) {
		set("latitude", latitude);
	}

	public java.math.BigDecimal getLatitude() {
		return get("latitude");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
