package com.shangsc.platform.model.base;

import com.shangsc.platform.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLoginRecord<M extends BaseSysLoginRecord<M>> extends BaseModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setSysUid(Integer sysUid) {
		set("sys_uid", sysUid);
	}

	public Integer getSysUid() {
		return get("sys_uid");
	}

	public void setLoginDate(java.util.Date loginDate) {
		set("login_date", loginDate);
	}

	public java.util.Date getLoginDate() {
		return get("login_date");
	}

	public void setLoginErrTimes(Integer loginErrTimes) {
		set("login_err_times", loginErrTimes);
	}

	public Integer getLoginErrTimes() {
		return get("login_err_times");
	}

	public void setLoginStatus(Integer loginStatus) {
		set("login_status", loginStatus);
	}

	public Integer getLoginStatus() {
		return get("login_status");
	}

}
