package com.shangsc.platform.model.base;

import com.shangsc.platform.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppVersion<M extends BaseAppVersion<M>> extends BaseModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setLinkUrl(String linkUrl) {
		set("link_url", linkUrl);
	}

	public String getLinkUrl() {
		return get("link_url");
	}

	public void setNatureNo(Integer natureNo) {
		set("nature_no", natureNo);
	}

	public Integer getNatureNo() {
		return get("nature_no");
	}

	public void setOs(String os) {
		set("os", os);
	}

	public String getOs() {
		return get("os");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setVersionNo(String versionNo) {
		set("version_no", versionNo);
	}

	public String getVersionNo() {
		return get("version_no");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setIsForce(Integer isForce) {
		set("is_force", isForce);
	}

	public Integer getIsForce() {
		return get("is_force");
	}

}
