package com.shangsc.platform.model.base;

import com.shangsc.platform.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDictData<M extends BaseDictData<M>> extends BaseModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setValue(String value) {
		set("value", value);
	}

	public String getValue() {
		return get("value");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setSeq(Integer seq) {
		set("seq", seq);
	}

	public Integer getSeq() {
		return get("seq");
	}

	public void setUpdateTime(Integer updateTime) {
		set("update_time", updateTime);
	}

	public Integer getUpdateTime() {
		return get("update_time");
	}

	public void setDictTypeId(Integer dictTypeId) {
		set("dict_type_id", dictTypeId);
	}

	public Integer getDictTypeId() {
		return get("dict_type_id");
	}

}
