package com.shangsc.platform.model.base;

import com.shangsc.platform.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaterIndex<M extends BaseWaterIndex<M>> extends BaseModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setInnerCode(String innerCode) {
		set("inner_code", innerCode);
	}

	public String getInnerCode() {
		return get("inner_code");
	}

	public void setWatersType(Integer watersType) {
		set("waters_type", watersType);
	}

	public Integer getWatersType() {
		return get("waters_type");
	}

	public void setWaterIndex(java.math.BigDecimal waterIndex) {
		set("water_index", waterIndex);
	}

	public java.math.BigDecimal getWaterIndex() {
		return get("water_index");
	}

	public void setJanuary(java.math.BigDecimal january) {
		set("january", january);
	}

	public java.math.BigDecimal getJanuary() {
		return get("january");
	}

	public void setFebruary(java.math.BigDecimal february) {
		set("february", february);
	}

	public java.math.BigDecimal getFebruary() {
		return get("february");
	}

	public void setMarch(java.math.BigDecimal march) {
		set("march", march);
	}

	public java.math.BigDecimal getMarch() {
		return get("march");
	}

	public void setApril(java.math.BigDecimal april) {
		set("april", april);
	}

	public java.math.BigDecimal getApril() {
		return get("april");
	}

	public void setMay(java.math.BigDecimal may) {
		set("may", may);
	}

	public java.math.BigDecimal getMay() {
		return get("may");
	}

	public void setJune(java.math.BigDecimal june) {
		set("june", june);
	}

	public java.math.BigDecimal getJune() {
		return get("june");
	}

	public void setJuly(java.math.BigDecimal july) {
		set("july", july);
	}

	public java.math.BigDecimal getJuly() {
		return get("july");
	}

	public void setAugust(java.math.BigDecimal august) {
		set("august", august);
	}

	public java.math.BigDecimal getAugust() {
		return get("august");
	}

	public void setSeptember(java.math.BigDecimal september) {
		set("september", september);
	}

	public java.math.BigDecimal getSeptember() {
		return get("september");
	}

	public void setOctober(java.math.BigDecimal october) {
		set("october", october);
	}

	public java.math.BigDecimal getOctober() {
		return get("october");
	}

	public void setNovember(java.math.BigDecimal november) {
		set("november", november);
	}

	public java.math.BigDecimal getNovember() {
		return get("november");
	}

	public void setDecember(java.math.BigDecimal december) {
		set("december", december);
	}

	public java.math.BigDecimal getDecember() {
		return get("december");
	}

}
