package com.shangsc.platform.model.base;

import com.shangsc.platform.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRes<M extends BaseSysRes<M>> extends BaseModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setPid(Integer pid) {
		set("pid", pid);
	}

	public Integer getPid() {
		return get("pid");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setDes(String des) {
		set("des", des);
	}

	public String getDes() {
		return get("des");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setIconCls(String iconCls) {
		set("iconCls", iconCls);
	}

	public String getIconCls() {
		return get("iconCls");
	}

	public void setSeq(Integer seq) {
		set("seq", seq);
	}

	public Integer getSeq() {
		return get("seq");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setModifydate(java.util.Date modifydate) {
		set("modifydate", modifydate);
	}

	public java.util.Date getModifydate() {
		return get("modifydate");
	}

	public void setEnabled(Integer enabled) {
		set("enabled", enabled);
	}

	public Integer getEnabled() {
		return get("enabled");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}

	public Integer getLevel() {
		return get("level");
	}

}
